version: '3'
services:
  blanded_learning_backend:
    container_name: blanded_learning_backend
    restart: always
    ports:
      - "8082:8082"
    image: rmakaoui/mybackend:4.0  # Update this line with the correct image name and tag
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  blanded_learning_frontend:
    container_name: blanded_learning_frontend
    image: rmakaoui/myfrontend:10.0  # Update this line with the correct image name and tag
    ports:
      - 4200:80
    depends_on:
      - blanded_learning_backend
    networks:
      - app-network

volumes:
  mysql:

networks:
  app-network:
    driver: bridge
